// Generated by CoffeeScript 1.10.0
(function() {
  var _ol, div, div2, li, li_2, newLi, textElem;

  div = document.createElement('div');

  div.className = "alert alert-success";

  div.innerHTML = "<strong>good!</strong> HELLO";

  document.body.appendChild(div);

  textElem = document.createTextNode('Тут был я');

  document.body.insertBefore(textElem, document.body.firstChild);

  newLi = document.createElement('li');

  newLi.innerHTML = 'Привет, мир!';

  _ol = document.getElementById("_ol") || get.getElementsByTagName('ol');

  console.log(_ol);

  _ol.appendChild(newLi);

  _ol.insertBefore(newLi, _ol.children[2]);

  div2 = div.cloneNode(true);

  div2.querySelector('strong').innerHTML = 'Супер!';

  div.parentNode.insertBefore(div2, div.nextSibling);

  li = _ol.getElementsByTagName('li');

  console.log(li);

  li_2 = document.createElement('li');

  li_2.innerHTML = 'Hello';

  _ol.removeChild(li[0]);

  _ol.replaceChild(li_2, li[2]);

}).call(this);
